theme: jekyll-theme-hacker
title: here goes nothing... literally, because I my value... well wait sorry I meant because I have no value.
description: this site will have so much information, pictures, programming projects, peronal ideas, etc; HOWEVER,
    the ultimate question is, are you willing to risk your reputation to confirm your oh-so-adamant points of view?
    You really think you are not racist? Simply prove it using a test on this site.  Oh, the only thing, your results will
    be permanently uploaded to Facebook, Instagram, and multiple other social media sites.  But hey, you're a good person,
    you got this.
