theme: jekyll-theme-hacker
title: readme for a project on github with link to the full project files
description: just the description, etc of what has been completed so far for a separate project on github, with a link to the actual projec itself.
